=== Oisota/Breakout/breakout/resources/levels/level.dtd
<!DOCTYPE level [
    <!ELEMENT level (name,difficulty,ball_speed,next,bricks)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT difficulty (#PCDATA)>
    <!ELEMENT ball_speed (#PCDATA)>
    <!ELEMENT next (#PCDATA)>
    <!ELEMENT bricks (row+)>
    <!ELEMENT row (column+)>
    <!ELEMENT column (#PCDATA)>
    <!ATTLIST column color (red|orange|yellow|green|blue|black|grey|tan|white) #REQUIRED>
]>

=== Oisota/Breakout/breakout/resources/levels/level_9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <name>Level Nine</name>
    <difficulty>hard</difficulty>
    <ball_speed>13</ball_speed>
    <next>level_1.xml</next>
    <bricks> 
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
        <row>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
            <column color="white">1</column>
        </row>
    </bricks>        
</level>

=== Oisota/Breakout/resources/levels/level_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <name>Level Eight</name>
    <difficulty>hard</difficulty>
    <ball_speed>12</ball_speed>
    <next>level_9.xml</next>
    <bricks>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
        <row>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
            <column color="yellow">1</column>
        </row>
    </bricks>        
</level>

=== Oisota/Breakout/breakout/resources/levels/level_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <name>Level One</name>
    <difficulty>easy</difficulty>
    <ball_speed>5</ball_speed>
    <next>level_2.xml</next>
    <bricks>
        <row>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
        </row>
        <row>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
            <column color="red">1</column>
        </row>
    </bricks>        
</level>

=== Oisota/Breakout/breakout/resources/levels/level_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <name>Level Three</name>
    <difficulty>easy</difficulty>
    <ball_speed>7</ball_speed>
    <next>level_4.xml</next>
    <bricks>
        <row>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
        </row>
        <row>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
        </row>
        <row>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
        </row>
        <row>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
        </row>
        <row>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
        </row>
        <row>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
            <column color="green">1</column>
        </row>
    </bricks>        
</level>

=== Oisota/Breakout/breakout/resources/levels/level_7.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE level SYSTEM "level.dtd">
<level>
    <name>Level Seven</name>
    <difficulty>hard</difficulty>
    <ball_speed>11</ball_speed>
    <next>level_8.xml</next>
    <bricks>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
        <row>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
            <column>tan</column>
        </row>
    </bricks>        
</level>
